
version: '3.8'

services:
  starbucks-app:
    image: ${DOCKERHUB_CREDENTIALS_USR:-your-dockerhub-username}/starbucks-app:${DOCKER_TAG:-latest}
    container_name: starbucks-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app-network:
    driver: bridge
